name: 'ro-crate-preview'
description: 'This creates a preview html file from RO-Crate Metadata File (ro-crate-metadata.json)'
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  crate_path:
    description: 'Path to RO-Crate Root folder'
    required: false
    default: '.'
outputs:
  preview:
    description: 'HTML preview of the RO Crate'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.crate_path }}
